server:
  port: 8282
spring:
#--database--
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/yihuobaodb
   username: root
   password: 200502

#--mail--
  mail:
    protocol: smtps
    host: smtp.qq.com
    port: 465
    username: 3488570183@qq.com
    password: zgnmbtmkvunpdbbc
    default-encoding: utf-8

#--redis--
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    key:
      prefix:
        authCode: "portal:authCode:"
      expire:
        authCode: 120 # 验证码超期时间


properties:
  mail:
    smtp:
      socketFactoryClass: javax.net.ssl.SSLSocketFactory
      ssl: true
      debug: true

#--mybatis--
mybatis:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/**/*.xml,classpath*:com/yihuobao/yhb/mapper/**/*.xml
  type-aliases-package: com.yihuobao.yhb.entity.po
  table:
    auto: none
  model:
    pack: com.yihuobao.yhb.entity.po
  database:
    type: mysql
actable:
  entity:
    package: com.yihuobao.yhb.entity.po
#--dift--
dify:
  url: http://106.53.46.231:8000/v1/chat-messages
  key:
    test: app-xnhpDbVNJcsSFh6XPEBBXgne